[project]
name = "penguins-xgboost-project"
version = "0.1.0"
dependencies = [
  "xgboost==2.1.1",    # Latest as of May 2025
  "pandas==2.2.2",     # Latest as of May 2025
  "scikit-learn==1.5.1",  # For dataset splitting
  "seaborn==0.13.2"    # For penguins dataset
]
